node:
    build: .
    dockerfile: node.dockerfile
    ports:
        - 8080:3000
    volumes:
        - ./web:/web
    links:
        - db:mongo_db
db:
    build: .
    dockerfile: db.dockerfile
    ports:
        - 27017:27017
# Using volumes on windows can be an issue
    # volumes:
    #     - ./db:/data/db
